### ISSUE TITLE
Class: sign up

### ISSUE THREAD

**Issue by wasabi233** [Dai0526/ASE-Fall2016#1]
## collaborators

**Comment by Dai0526** [comment]
I can't open the sqliste version. I attached the error message. 
![1111](https://cloud.githubusercontent.com/assets/11875911/19580752/5d247cdc-96f6-11e6-93b8-9bfee1fda8c6.png)

**Comment by wasabi233** [comment]
119 是他范例里的诶 你init database了么?

**Comment by Dai0526** [comment]
Cool~
