### ISSUE TITLE
Please add the test case for logout caching

### ISSUE THREAD

**Issue by Dai0526** [Dai0526/ASE-Fall2016#6]
Fixing the problem that the back button will keep the cache for the previous page after using login.
Please can someone add the unittest case for it?Thanks.

![screenshot](https://cloud.githubusercontent.com/assets/11875911/20236780/f5172c80-a88d-11e6-9983-fb80d156a8a1.jpg)

TA说的那个logout后返回键保留cache的问题解决了。
麻烦谁写下testcase。谢谢！

**Comment by wasabi233** [comment]
Added. Please review the new [test cases](https://github.com/Dai0526/ASE-Fall2016/blob/master/project/test_flaskr.py).
